name: ci
on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
      - tmp/mac-hac
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-16.04
          #- windows-latest
        python:
          - 3.7.7
    env:
      GDC_CLIENT_ZIP: "gdc-client.zip"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      if: matrix.os != 'macos-latest'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    # setup-python uses GitHub-provided Python builds that only run on
    # macOS 10.14 and newer. To support older macOS versions, download
    # and install the official build from python.org instead.
    - name: Download and install macOS Python ${{ matrix.python }}
      if: matrix.os == 'macos-latest'
      run: |
        wget https://www.python.org/ftp/python/${{ matrix.python }}/python-${{ matrix.python }}-macosx10.9.pkg
        sudo installer -pkg python-${{ matrix.python }}-macosx10.9.pkg -target /
        rm python-${{ matrix.python }}-macosx10.9.pkg
        sudo ln -fs /usr/local/bin/python3 /usr/local/bin/python

        python --version
        hash python
        python --version

    - name: Run Tests
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox virtualenv
        tox -e py3
    - name: Package
      env:
        GDC_CLIENT_NO_ZIP: true
      run: |
        cd bin
        . ./package
        echo ::set-env name=GDC_CLIENT_ZIP::$GDC_CLIENT_ZIP
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.GDC_CLIENT_ZIP }}-py${{ matrix.python }}-${{ matrix.os }}-TEST
        path: bin/gdc-client
